# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            InchJS
tagline:          'A documentation measurement tool for JavaScript/NodeJS'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         100

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
